### ISSUE TITLE
[GP][Overall]: Does the game have the leagal rights to use the Star Wars name?

### ISSUE THREAD

**Issue by RosinaD** [shyZombie/StarWars-Crush2D02#1]
Does the game have legal rights to use the Star Wars name?

Registered in version  0.0.0.0.0.0.1 too early alpha.

**Comment by shyZombie** [comment]
The Star Wars brand is used just for inspiration. The final release of the game will be with the different name, or if Mr. Lukas gives his permision, because he trully enjoys the game - the SW brande will then stay.

**Comment by RosinaD** [comment]
Hello, 
It is still a good idea to change the name to avoid claims of legal rights from Mr. Lucas, not only waiting on his good will ;)

**Comment by shyZombie** [comment]
Will do in the next committed version! :)

**Comment by RosinaD** [comment]
Hello, 
Confirmed. The issue will be re- opened upon committing the next version.
Regards :)
